export type Language = 'en' | 'ru';
export const copy = {
  en: {
    skip:'Skip to content', home:'SONO home', nav:'Main navigation', speaker:'The speaker', models:'Compare models', setup:'Your setup', language:'Language', bag:'Bag', openBag:'Open bag, {count} speakers',
    eyebrow:'SONO ONE / WIRELESS SPEAKER', hero1:'Small footprint.', hero2:'Full-room sound.', intro1:'A little more music. A little less clutter.', intro2:'A portable speaker for the spaces you make your own.', build:'Build your setup', from:'From', heroAlt:'Cobalt SONO speakers, with woven fabric fronts and machined rear housing', render:'Front & rear views',
    conceptSpecs:'SONO One specifications', batteryFeature:'24-hour listening', batteryNote:"A day's music, away from the socket", usbFeature:'USB-C charging', usbNote:'A familiar cable. A simpler setup.', stereoFeature:'Wireless stereo', stereoNote:'Pair two for left & right sound',
    fit:'01 / FIND YOUR FIT', rhythm:'Room for your rhythm.', modelsIntro1:'Two sizes. One considered design.', modelsIntro2:'Choose the size that suits your space.', compact:'01 / COMPACT', fuller:'02 / FULLER SOUND', oneCaption:'A little speaker. A lot of possibility.', plusCaption:'More depth. More room to move.', oneUse:'Desks, shelves & slow mornings', plusUse:'Living rooms & shared spaces', choose:'Choose {model}', modelAlt:'{model}, front and rear views', output:'output', battery:'battery', hours:'hours', watts:'W', grams:'g', mm:'mm', selected:'Selected for your setup', compare:'Compare every detail', scrollCompare:'Scrollable model comparison', tableCaption:'Compare power, battery life and size.', spec:'Specification', outputSpec:'Output', batterySpec:'Battery life', weightSpec:'Weight', dimensionsSpec:'Dimensions', madeFor:'Made for',
    own:'02 / YOUR SOUND, YOUR SPACE', own1:'Make it', own2:'your own.', ownIntro1:'One for your desk. Two for your room.', ownIntro2:'Choose your finish and build your setup.', each:'/ each', perUnit:'each', finishAlt:'{model} in {colour}', finishPreview:'Finish', finish:'Finish', cobalt:'Cobalt', chalk:'Chalk', graphite:'Graphite', speakers:'Speakers', pair:'A stereo pair', limit:'Choose 1–4 speakers', decrease:'Decrease quantity', increase:'Increase quantity', quantity:'Speaker quantity', total:'Total', add:'Add to bag', saved:'Configuration saved on this device.', unsaved:'Your selection is available for this visit.', reset:'Reset configuration',
    talk:"03 / LET'S TALK SETUP", contact1:'A setup that', contact2:'fits your space.', contactIntro1:'Tell us where your music lives.', contactIntro2:'Prepare an enquiry with your chosen setup.', formNote:'Create an enquiry to review here. It will not be sent.', name:'Your name', namePlaceholder:'Alex Morgan', email:'Email address', space:'Your space', optional:'(optional)', spacePlaceholder:'A desk by the window, a small living room…', nameError:'Enter a name with at least 2 characters.', emailError:'Enter an email such as alex@example.com.', checkContact:'Check your contact details', preview:'Prepare enquiry', ready:'Enquiry prepared', prepared:'Prepared for {name}: {quantity} × {model} in {colour}, {price}. Contact: {email}.', yourSpace:'Your space: {space}.', localResult:'Your enquiry is ready to review. It has not been sent.',
    footer:'Sound for the spaces you make your own.', yourBag:'Your bag', closeBag:'Close bag', bagIntro:'Your chosen speakers.', emptyTitle:'A little room for sound.', empty:'Your bag is empty.', explore:'Explore the speakers', bagAlt:'{model} in {colour}', removeOne:'Remove one {model} {colour}', addOne:'Add one {model} {colour}', subtotal:'Subtotal', bagNote:'Your selection is kept until the page is refreshed.', continue:'Continue configuring', clear:'Clear bag', title:'SONO — Sound for your space', description:'Explore SONO wireless speakers, compare models and choose the setup that fits your space.'
  },
  ru: {
    skip:'Перейти к содержимому', home:'SONO — главная', nav:'Основная навигация', speaker:'О колонке', models:'Сравнить модели', setup:'Ваша конфигурация', language:'Язык', bag:'Корзина', openBag:'Открыть корзину, колонок: {count}',
    eyebrow:'SONO ONE / БЕСПРОВОДНАЯ КОЛОНКА', hero1:'Компактная форма.', hero2:'Объёмный звук.', intro1:'Больше музыки. Меньше лишнего.', intro2:'Портативная колонка для пространства, которое вы создаёте для себя.', build:'Выбрать конфигурацию', from:'От', heroAlt:'Кобальтовые колонки SONO: тканевая решётка спереди и металлический корпус сзади', render:'Вид спереди и сзади',
    conceptSpecs:'Характеристики SONO One', batteryFeature:'24 часа музыки', batteryNote:'Целый день без привязки к розетке', usbFeature:'Зарядка USB-C', usbNote:'Привычный кабель. Простое подключение.', stereoFeature:'Беспроводное стерео', stereoNote:'Две колонки — левый и правый каналы',
    fit:'01 / ВЫБЕРИТЕ СВОЮ МОДЕЛЬ', rhythm:'Звук в вашем ритме.', modelsIntro1:'Два размера. Продуманный дизайн.', modelsIntro2:'Выберите размер для вашего пространства.', compact:'01 / КОМПАКТНАЯ', fuller:'02 / БОЛЬШЕ ЗВУКА', oneCaption:'Маленькая колонка. Большие возможности.', plusCaption:'Глубже звук. Больше пространства.', oneUse:'Для рабочего стола, полки и неспешного утра', plusUse:'Для гостиной и общих пространств', choose:'Выбрать {model}', modelAlt:'{model}: вид спереди и сзади', output:'мощность', battery:'автономность', hours:'ч', watts:'Вт', grams:'г', mm:'мм', selected:'Выбрана для вашей конфигурации', compare:'Сравнить все характеристики', scrollCompare:'Сравнение моделей с горизонтальной прокруткой', tableCaption:'Сравните мощность, автономность и размеры.', spec:'Характеристика', outputSpec:'Мощность', batterySpec:'Автономность', weightSpec:'Вес', dimensionsSpec:'Размеры', madeFor:'Для каких пространств',
    own:'02 / ВАШ ЗВУК, ВАШЕ ПРОСТРАНСТВО', own1:'Соберите', own2:'свой вариант.', ownIntro1:'Одна — для стола. Две — для комнаты.', ownIntro2:'Выберите цвет и соберите конфигурацию.', each:'/ за штуку', perUnit:'за штуку', finishAlt:'{model}, цвет «{colour}»', finishPreview:'Цвет', finish:'Цвет', cobalt:'Кобальт', chalk:'Мел', graphite:'Графит', speakers:'Колонки', pair:'Стереопара', limit:'Выберите от 1 до 4 колонок', decrease:'Уменьшить количество', increase:'Увеличить количество', quantity:'Количество колонок', total:'Итого', add:'В корзину', saved:'Конфигурация сохранена на этом устройстве.', unsaved:'Ваш выбор доступен до закрытия страницы.', reset:'Сбросить конфигурацию',
    talk:'03 / ОБСУДИМ ВАШ ВАРИАНТ', contact1:'Звук для', contact2:'вашего пространства.', contactIntro1:'Расскажите, где будет звучать музыка.', contactIntro2:'Сформируйте обращение с выбранной конфигурацией.', formNote:'Сформируйте обращение для просмотра. Оно не будет отправлено.', name:'Ваше имя', namePlaceholder:'Александр Иванов', email:'Электронная почта', space:'Ваше пространство', optional:'(необязательно)', spacePlaceholder:'Стол у окна, небольшая гостиная…', nameError:'Введите имя длиной не менее 2 символов.', emailError:'Введите адрес почты, например alex@example.com.', checkContact:'Проверьте контактные данные', preview:'Сформировать обращение', ready:'Обращение сформировано', prepared:'Для {name}: {quantity} × {model}, цвет «{colour}», {price}. Контакт: {email}.', yourSpace:'Ваше пространство: {space}.', localResult:'Обращение готово для просмотра. Оно не отправлено.',
    footer:'Звук для пространства, которое вы создаёте.', yourBag:'Ваша корзина', closeBag:'Закрыть корзину', bagIntro:'Выбранные колонки.', emptyTitle:'Здесь есть место для музыки.', empty:'Ваша корзина пуста.', explore:'Посмотреть колонки', bagAlt:'{model}, цвет «{colour}»', removeOne:'Убрать одну колонку {model}, {colour}', addOne:'Добавить одну колонку {model}, {colour}', subtotal:'Итого', bagNote:'Подборка сохранена до перезагрузки страницы.', continue:'Продолжить выбор', clear:'Очистить корзину', title:'SONO — Звук для вашего пространства', description:'Беспроводные колонки SONO. Сравните модели и соберите конфигурацию для вашего пространства.'
  }
} as const;
export type CopyKey = keyof typeof copy.en;
export function translate(language: Language, key: CopyKey, values: Record<string, string | number> = {}) {
  return (copy[language][key] as string).replace(/\{(\w+)\}/g, (match, name: string) => String(values[name] ?? match));
}
export function restoreLanguage(): Language {
  try { return localStorage.getItem('sono.language.v1') === 'ru' ? 'ru' : 'en'; } catch { return 'en'; }
}

