import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Truck,CreditCard,ShieldCheck,RotateCcw,Headphones,Package,ArrowRight} from 'lucide-react';
import {Breadcrumb,ServiceStrip} from '@/components/store-ui';
import {servicePages} from '@/lib/service-content';
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const page=servicePages[slug];if(!page)notFound();const Icon=({delivery:Truck,payment:CreditCard,warranty:ShieldCheck,returns:RotateCcw,contacts:Headphones} as Record<string,typeof Truck>)[slug]||Package;
 return <div className="container page"><Breadcrumb items={[{label:page.label}]}/><header className="service-page-hero"><span className="icon-disc"><Icon size={35}/></span><p className="eyebrow">Сервис VELMREN</p><h1>{page.title}</h1><p>{page.intro}</p></header><div className="service-layout"><nav aria-label="Сервисные разделы">{Object.entries(servicePages).slice(0,6).map(([key,p])=><Link className={slug===key?'active':''} aria-current={slug===key?'page':undefined} href={`/service/${key}`} key={key}>{p.label}<ArrowRight size={14}/></Link>)}</nav><div className="service-content">{page.options.length>0&&<div className="service-options">{page.options.map(o=><article className="service-option" key={o.title}><h2>{o.title}</h2><p>{o.text}</p><b>{o.detail}</b></article>)}</div>}{page.sections.map(s=><section className="service-section" key={s.title}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.items&&<ul>{s.items.map(i=><li key={i}>{i}</li>)}</ul>}</section>)}{page.note&&<aside className="service-note"><strong>Обратите внимание</strong>{page.note}</aside>}{page.faq.length>0&&<section className="service-faq"><h2>Частые вопросы</h2>{page.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>}<div className="service-contact-cta"><div><h3>Остался вопрос?</h3><p>Опишите ситуацию — сохраним переписку и поможем разобраться.</p></div><Link className="button" href="/support">Написать в поддержку <ArrowRight size={16}/></Link></div></div></div><ServiceStrip/></div>
}
