'use client';
import Link from 'next/link';
import {useState, type ReactNode, type InputHTMLAttributes} from 'react';
import {ArrowRight, Check, ShieldCheck, Truck, RotateCcw, Headphones, Package, LoaderCircle} from 'lucide-react';
import {api,money,useResource,notify,refreshStore,addToCart} from '@/lib/client';
import type {Product,Variant} from '@/lib/types';
export type Address={id?:string;name:string;phone:string;city:string;street:string;postalCode?:string;isDefault?:boolean;email?:string;contact?:{name:string;phone:string;email:string};recipient?:{name:string;phone:string};pickupPoint?:string};
export type Profile={id:string;name:string;email:string;phone:string;role:string;bonuses:number;settings:Record<string,boolean>;addresses:Address[]};
export type Cart={id:string;items:{id:string;variantId:string;quantity:number;availabilityError?:string|null;variant:Variant;product:Product;lineTotal:number}[];subtotal:number;discount:number;shipping:number;total:number;promoCode?:string;promoError?:string|null};
export type Order={id:string;number:string;status:string;paymentStatus:string;paymentMethod:string;deliveryMethod:string;subtotal:number;discount:number;shipping:number;total:number;address:Address;items:{id:string;productId:string;variantId:string;name:string;slug:string;image:string;color:string;storage:string;price:number;quantity:number}[];events:{id:string;status:string;message:string;createdAt:string}[];createdAt:string;trackingNumber?:string;testMode:boolean;isGuest?:boolean;comment?:string};
export const states:Record<string,string>={PENDING_PAYMENT:'Ожидает оплаты',PROCESSING:'В обработке',SHIPPED:'Доставляется',DELIVERED:'Доставлен',CANCELLED:'Отменён',PENDING:'Ожидает оплаты',PAID:'Оплачен',FAILED:'Оплата не прошла',REFUNDED:'Средства возвращены',APPROVED:'Опубликован',REJECTED:'Отклонён',OPEN:'Открыто',CLOSED:'Закрыто',RESOLVED:'Решено'};
export const payNames:Record<string,string>={card:'Банковской картой',sbp:'Система быстрых платежей',cash:'При получении'};
export const date=(value:string)=>new Date(value).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});
export function useAction(){const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function run<T,>(fn:()=>Promise<T>,success?:string){setBusy(true);setError('');try{const value=await fn();if(success)notify(success);return value}catch(e){setError((e as Error).message);return undefined}finally{setBusy(false)}}return {busy,error,run,setError};}
export function ErrorBox({error}:{error?:string}){return error?<div className="commerce-error" role="alert">{error}</div>:null}
export function Loading(){return <div className="commerce-loading" role="status"><LoaderCircle className="spin"/> Загружаем данные…</div>}
export function PageHead({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <><nav className="commerce-crumb" aria-label="Навигационная цепочка"><Link href="/">Главная</Link><span>›</span><span>{title}</span></nav><header className="commerce-heading"><div><h1>{title}</h1>{subtitle&&<p className="muted">{subtitle}</p>}</div>{action}</header></>}
export function Section({title,icon,children}:{title:string;icon?:ReactNode;children:ReactNode}){return <section className="commerce-section panel"><h2>{icon&&<span className="commerce-icon">{icon}</span>}{title}</h2><div className="commerce-section-body">{children}</div></section>}
export function Field({label,error,...props}:InputHTMLAttributes<HTMLInputElement>&{label:string;error?:string}){return <label className="field commerce-field"><span>{label}{props.required&&<span aria-hidden="true"> *</span>}</span><input {...props} aria-label={label} aria-invalid={!!error}/>{error&&<small className="commerce-field-error">{error}</small>}</label>}
export function Status({value}:{value:string}){return <span className={`commerce-status ${['PAID','DELIVERED','APPROVED'].includes(value)?'good':['CANCELLED','FAILED','REJECTED'].includes(value)?'bad':''}`}>{states[value]||value}</span>}
export function Empty({title,text,href='/catalog',link='Перейти в каталог'}:{title:string;text:string;href?:string;link?:string}){return <div className="empty-state commerce-empty"><Package size={42}/><h2>{title}</h2><p className="muted">{text}</p><Link className="button" href={href}>{link}<ArrowRight size={17}/></Link></div>}
export function AuthGate({next}:{next:string}){return <Empty title="Войдите в личный кабинет" text="Сохраните покупки, адреса и историю заказов в одном месте." href={`/auth?next=${encodeURIComponent(next)}`} link="Войти или зарегистрироваться"/>}
export function Totals({subtotal,discount,shipping,total}:{subtotal:number;discount:number;shipping:number;total:number}){return <dl className="commerce-totals"><div><dt>Товары</dt><dd>{money(subtotal)}</dd></div><div><dt>Скидка</dt><dd className={discount?'commerce-green':''}>{discount?'− ':''}{money(discount)}</dd></div><div><dt>Доставка</dt><dd className={!shipping?'commerce-green':''}>{shipping?money(shipping):'Бесплатно'}</dd></div><div className="grand"><dt>Итого</dt><dd>{money(total)}</dd></div></dl>}
export function Assurance(){return <div className="commerce-assurances">{[[ShieldCheck,'Безопасная оплата','Удобный способ на ваш выбор'],[Truck,'Бережная доставка','Курьером или в пункт выдачи'],[RotateCcw,'Простой возврат','Поможем с обращением']].map(([Icon,title,text])=>{const I=Icon as typeof ShieldCheck;return <div key={String(title)}><span className="commerce-icon"><I/></span><div><strong>{String(title)}</strong><p>{String(text)}</p></div></div>})}</div>}
export function Help(){return <div className="commerce-help"><span className="commerce-icon"><Headphones/></span><div><h3>Нужна помощь?</h3><p className="muted">Поможем с выбором и вашим заказом</p></div><Link className="button secondary" href="/support">Написать в поддержку <ArrowRight size={16}/></Link></div>}
export function Recommendations(){const {data}=useResource<{products:Product[]}>('/api/catalog?limit=5');const a=useAction();return data?.products.length?<section className="commerce-recommendations"><div className="commerce-heading"><h2>Вам может понравиться</h2><Link href="/catalog">Смотреть всё →</Link></div><ErrorBox error={a.error}/><div className="commerce-product-grid">{data.products.map(p=><article key={p.id}><Link href={`/product/${p.slug}`}><img src={p.images[0]} alt={p.name}/><h3>{p.name}</h3></Link><p className="muted">{p.reviewCount?<><span className="commerce-star">★</span> {p.rating.toFixed(1)} · {p.reviewCount} отзывов</>:'Пока нет отзывов'}</p><strong>{money(p.price)}</strong><button className="button" disabled={a.busy||!p.variants.some(v=>v.stock>0)} onClick={()=>a.run(()=>addToCart(p.variants.find(v=>v.stock>0)!.id))}>В корзину</button></article>)}</div></section>:null}
export function OrderItems({order}:{order:Order}){return <div className="commerce-order-items">{order.items.map(item=><div className="commerce-mini-item" key={item.id}><Link href={`/product/${item.slug}`}><img src={item.image} alt={item.name}/></Link><div><Link href={`/product/${item.slug}`}><strong>{item.name}</strong></Link><p className="muted">{[item.color,item.storage].filter(Boolean).join(' · ')}</p></div><small>{item.quantity} шт.</small><strong>{money(item.price*item.quantity)}</strong></div>)}</div>}
export function Timeline({order}:{order:Order}){const steps=['PENDING_PAYMENT','PROCESSING','SHIPPED','DELIVERED'];const active=steps.indexOf(order.status);return <div className="commerce-timeline">{steps.map((step,i)=><div className={i<=active?'complete':''} key={step}><span>{i<=active?<Check size={18}/>:i+1}</span><strong>{step==='PENDING_PAYMENT'&&order.paymentMethod==='cash'?'Заказ оформлен':states[step]}</strong><small>{order.events.find(e=>e.status===step)?date(order.events.find(e=>e.status===step)!.createdAt):step==='PENDING_PAYMENT'?date(order.createdAt):'Ожидается'}</small></div>)}</div>}
