'use client';
import Link from 'next/link';
import {FavoritesPage} from '@/components/saved-lists';
import {useParams,useRouter} from 'next/navigation';
import {User,Package,MapPin,Heart,Star,Settings,LogOut,ShieldCheck} from 'lucide-react';
import {api,useResource,refreshStore,clearFavoritesOnLogout} from '@/lib/client';
import {type Profile,PageHead,Loading,AuthGate,Help,ErrorBox,useAction} from '@/components/commerce/common';
import {ProfileForm,Addresses,AccountOrders,Bonuses,Settings as AccountSettings} from '@/components/commerce/account';
export default function AccountPage(){const params=useParams<{section?:string[]}>();const section=params.section?.[0]||'orders';const profile=useResource<Profile>('/api/profile');const router=useRouter();const a=useAction();const menu=[{id:'profile',label:'Профиль',Icon:User},{id:'orders',label:'Мои заказы',Icon:Package},{id:'addresses',label:'Адреса доставки',Icon:MapPin},{id:'favorites',label:'Избранное',Icon:Heart},{id:'bonuses',label:'Бонусы и скидки',Icon:Star},{id:'settings',label:'Настройки',Icon:Settings}];return <div className="container page"><PageHead title="Личный кабинет" subtitle="Управляйте заказами, данными и настройками в одном месте." action={profile.data&&<button className="button secondary" disabled={a.busy} onClick={()=>a.run(async()=>{await api('/api/auth/sign-out','POST',{});clearFavoritesOnLogout();refreshStore();router.push('/auth');router.refresh()})}><LogOut size={17}/>Выйти</button>}/><ErrorBox error={a.error}/>{profile.loading?<Loading/>:!profile.data?<AuthGate next={`/account/${section}`}/>:<><div className="commerce-account-layout"><aside className="commerce-account-sidebar"><div className="commerce-profile-card"><span className="commerce-icon"><User/></span><div><strong>{profile.data.name}</strong><small>{profile.data.email}</small></div></div><Link className="commerce-balance" href="/account/bonuses"><Star color="#efb324" fill="#efb324"/><span><small>Бонусный баланс</small><strong>{profile.data.bonuses.toLocaleString('ru-RU')}</strong></span><span>›</span></Link><nav aria-label="Личный кабинет">{menu.map(m=><Link className={section===m.id?'active':''} href={`/account/${m.id}`} key={m.id}><m.Icon size={21}/>{m.label}</Link>)}{['ADMIN','STAFF'].includes(profile.data.role)&&<Link href="/admin"><ShieldCheck size={21}/>Управление магазином</Link>}</nav><Help/></aside><div className="commerce-account-content">{section==='favorites'?<FavoritesPage embedded/>:section==='profile'?<ProfileForm profile={profile.data} reload={profile.reload}/>:section==='addresses'?<Addresses/>:section==='bonuses'?<Bonuses profile={profile.data}/>:section==='settings'?<AccountSettings profile={profile.data} reload={profile.reload}/>:<AccountOrders/>}</div></div>{section!=='bonuses'&&<Bonuses profile={profile.data}/>}</>}</div>}
