import Image from 'next/image';
import { Icon, type IconName } from './Icon';
import type { ProjectSection } from '@/lib/schema';
const Arrow = () => <Icon name="arrow"/>;
type CodeSection = Extract<ProjectSection, { kind: 'code' }>;
function CodePanel({ section }: { section: CodeSection }) {
  return <div className="code-panel"><a className="code-file" href={section.link.href}><span>{section.language || 'Код'}</span><span>{section.link.href.split('/').pop()?.split('#')[0] || 'Исходник'} ↗</span></a><pre><code>{section.code.split('\n').map((line, index) => <span className="code-line" key={index}><span className="line-number" aria-hidden="true">{index + 1}</span><span>{line.split(/\b(private|boolean|return)\b/g).map((token, j) => ['private', 'boolean', 'return'].includes(token) ? <span className="code-keyword" key={j}>{token}</span> : token)}</span></span>)}</code></pre><div className="code-note"><Icon name="check"/><div><h3>{section.title}</h3><p>{section.text}</p></div></div></div>;
}
export function Section({ section, relatedCode }: { section: ProjectSection; relatedCode?: CodeSection }) {
  switch (section.kind) {
    case 'media': return <figure className="hero-media"><Image {...section.image} priority sizes="(max-width: 1200px) 100vw, 1160px"/><figcaption>{section.caption}</figcaption></figure>;
    case 'features': return <section className="section feature-section"><div className="feature-intro"><div><h2>{section.title}</h2><p>{section.text}</p></div>{section.detailText && <p className="feature-summary">{section.detailText}</p>}</div><ul className="feature-cards">{section.items.map((item, index) => <li key={item}><Icon name={section.icons?.[index] || (['search', 'layers', 'calculator'] as IconName[])[index % 3]}/><div><h3>{item}</h3>{section.descriptions?.[index] && <p>{section.descriptions[index]}</p>}</div></li>)}</ul></section>;
    case 'mobile': return <section className="section mobile-section"><div className={`mobile-frame ${section.image.height > 1000 ? 'long-screen' : ''}`}><Image {...section.image} sizes="(max-width: 700px) 260px, 390px"/></div><div><p className="eyebrow">{section.image.width > section.image.height ? 'Широкое окно' : 'Мобильная компоновка'}</p><h2>{section.title}</h2><p>{section.text}</p><a className="underlink" href={section.link.href}>{section.link.label}<Arrow/></a></div></section>;
    case 'gallery': return <section className="section gallery" aria-label={section.title || 'Ход раунда'}><h2>{section.title || 'Вопрос, ответ и результат'}</h2><div className="gallery-grid">{section.items.map(item => <figure key={item.title}><div className="gallery-image"><Image {...item.image} sizes="(max-width: 700px) 100vw, 390px"/></div><figcaption><h3>{item.title}</h3><p>{item.text}</p></figcaption></figure>)}</div></section>;
    case 'flow': return <section id="scenario" className="flow-section" aria-label={section.title}><p className="eyebrow">Процесс</p><h2>{section.title}</h2><ol>{section.items.map((item, i) => <li key={item.title}>{item.image ? <div className="phase-image"><Image {...item.image} sizes="(max-width: 700px) 100vw, 390px"/></div> : item.diagram && <div className={`phase-diagram ${item.diagram.kind}`} aria-label="Схема условия фазы"><span className="phase-symbol"><Icon name={item.diagram.kind === 'complete' ? 'check' : item.diagram.kind === 'objectives' ? 'core' : 'layers'}/></span><div>{item.diagram.labels.map(label => <span key={label}>{label}</span>)}</div></div>}<div className="phase-caption"><span className="step-number">{i + 1}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></div></li>)}</ol></section>;
    case 'architecture': return <section className="section architecture"><p className="eyebrow">Архитектура</p><div className="architecture-heading"><h2>{section.title}</h2><p>{section.text}</p></div><div className="architecture-grid"><div className="architecture-list">{section.items.map((item, index) => <a className="architecture-item" href={item.link.href} key={item.title}><span className="architecture-icon"><Icon name={(['core', 'file', 'cube'] as IconName[])[index % 3]}/></span><div><h3>{item.title}</h3><p>{item.text}</p><span className="source-filename">{item.link.label}</span></div><Arrow/></a>)}</div>{relatedCode && <CodePanel section={relatedCode}/>}</div></section>;
    case 'code': return <section className="section code-section"><CodePanel section={section}/></section>;
    case 'links': return <section className={`section source-section${section.brand ? ' branded-source' : ''}`}><div className="source-heading">{section.brand ? <Image className="source-logo" {...section.brand.image} sizes="120px"/> : <span className="source-mark"><Icon name={section.links.some(link => link.label.includes('.ts')) ? 'file' : section.links.some(link => link.href.includes('github.com')) ? 'github' : 'layers'}/></span>}<div>{section.brand && <p className="eyebrow">{section.brand.eyebrow}</p>}<h2>{section.title}</h2>{section.text && <p>{section.text}</p>}{section.brand && <a className="logo-credit" href={section.brand.credit.href}>{section.brand.credit.label}</a>}</div></div><ul className="link-list">{section.links.map(link => <li key={link.href}><a href={link.href}><Icon name={link.label.includes('.ts') ? 'file' : /\.(zip|jar)$/.test(link.href) ? 'download' : /\.(mp4|webm)$/.test(link.href) ? 'play' : link.href.includes('github.com') ? 'github' : 'file'}/>{link.label}<Arrow/></a></li>)}</ul></section>;
  }
}
