import {createRequire} from 'node:module';import {createServer} from 'node:http';import {writeFileSync,mkdirSync} from 'node:fs';import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..'),require=createRequire(root+'/.runtime/tools/package.json');const mineflayer=require('mineflayer');
const bots={},records=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
for(const name of ['NPCAlpha','NPCBeta']){const b=mineflayer.createBot({host:'127.0.0.1',port:Number(process.env.NPC_SERVER_PORT??25579),username:name,version:process.env.NPC_CLIENT_VERSION??'1.21.11',auth:'offline'});bots[name]=b;b.on('spawn',()=>{records.push({name,type:'spawn'});console.log('NETWORK_PLAYER_READY',name);});b.on('message',(m)=>{records.push({name,type:'chat',text:m.toString()});if(m.toString().includes('[NPC]'))console.log(name,m.toString());});b.on('windowOpen',w=>{records.push({name,type:'menu',title:w.title,items:w.slots.slice(0,w.inventoryStart).map((i,index)=>i?{index,name:i.name,displayName:i.displayName,nbt:i.nbt}:null).filter(Boolean)});console.log('MENU_OPEN',name,w.title);});b.on('error',e=>console.error(name,e.message));b.on('kicked',r=>console.log('KICKED',name,JSON.stringify(r)));}
const api=createServer(async(req,res)=>{res.setHeader('content-type','application/json');if(req.method==='GET'){res.end(JSON.stringify({bots:Object.fromEntries(Object.entries(bots).map(([n,b])=>[n,{position:b.entity?.position,inventory:b.inventory?.items().map(i=>({name:i.name,count:i.count})),window:b.currentWindow?.title,entities:Object.values(b.entities??{}).filter(e=>e.name==='villager').map(e=>({id:e.id,position:e.position,name:e.name}))}])),records:records.slice(-100)}));return;}
let raw='';for await(const c of req)raw+=c;try{const a=JSON.parse(raw);const b=bots[a.name??'NPCAlpha'];switch(a.action){case 'chat':b.chat(a.text);break;case 'click':await b.clickWindow(a.slot,0,0);break;case 'close':if(b.currentWindow)b.closeWindow(b.currentWindow);break;case 'interact':{const e=Object.values(b.entities).filter(e=>e.name==='villager').sort((x,y)=>x.position.distanceTo(b.entity.position)-y.position.distanceTo(b.entity.position))[0];if(!e)throw Error('No visible villager');await b.activateEntity(e);break;}case 'end':for(const bot of Object.values(bots))bot.quit();api.close();break;default:throw Error('Unknown action');}await sleep(200);res.end(JSON.stringify({ok:true}));}catch(e){res.statusCode=400;res.end(JSON.stringify({error:String(e)}));}}).listen(Number(process.env.NPC_CLIENT_CONTROL??25590),'127.0.0.1',()=>console.log('NETWORK_CONTROL127.0.0.1:25590'));
process.on('exit',()=>{mkdirSync(root+'/build/verification',{recursive:true});writeFileSync(root+'/build/verification/network-client-log.json',JSON.stringify(records,null,2));});

