import {test,expect,type Page} from '@playwright/test';
import {demoPassword} from './credentials';
const output='E:/Astra/2026-09-26/realtime-voice-chat/outputs/electronics-store/revision/screenshots';
async function shot(page:Page,name:string){await expect(page.locator('.commerce-loading, .loading')).toHaveCount(0);await page.locator('img').evaluateAll(async images=>{images.forEach(i=>(i as HTMLImageElement).loading='eager');await Promise.all(images.map(i=>(i as HTMLImageElement).decode().catch(()=>{})))});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:`${output}/${name}.png`,fullPage:true,animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()}
test('Регистрация, профиль, адреса, настройки, модерация и изоляция избранного',async({page,browser})=>{
 // Signs in as administrator later on; skip up front when DEMO_PASSWORD is missing.
 demoPassword();
 const stamp=Date.now();const email=`browser-${stamp}@velmren.local`;const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/auth');await page.getByRole('button',{name:'Регистрация',exact:true}).click();await page.getByLabel('Ваше имя',{exact:true}).fill('Тестовый покупатель');await page.getByLabel('Электронная почта',{exact:true}).fill(email);await page.getByLabel('Пароль',{exact:true}).fill('BrowserCheck2026!');await page.getByRole('button',{name:'Создать аккаунт'}).click();await expect(page).toHaveURL(/account\/orders/);
 await page.goto('/account/profile');await page.getByLabel('Имя и фамилия',{exact:true}).fill('Покупатель E2E');await page.getByLabel('Телефон',{exact:true}).fill('+7 999 123-12-12');await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('status')).toContainText('Профиль обновлён');await page.reload();await expect(page.getByLabel('Имя и фамилия',{exact:true})).toHaveValue('Покупатель E2E');await shot(page,'11-profile-desktop');
 await page.goto('/account/addresses');await page.getByRole('button',{name:'Новый адрес'}).click();for(const [label,value] of [['Имя получателя','Покупатель E2E'],['Телефон','+7 999 123-12-12'],['Город','Казань'],['Улица, дом, квартира',`Улица Проверки, ${stamp}`]])await page.getByLabel(label,{exact:true}).fill(value);await page.getByRole('button',{name:'Сохранить адрес'}).click();await expect(page.locator('.commerce-address')).toHaveCount(1);await page.reload();await expect(page.locator('.commerce-address')).toContainText('Казань');await shot(page,'11-addresses-desktop');
 await page.goto('/account/settings');await page.getByLabel('Новости и персональные предложения',{exact:true}).check();await page.getByRole('button',{name:'Сохранить настройки'}).click();await expect(page.getByRole('status')).toContainText('Настройки сохранены');await page.reload();await expect(page.getByLabel('Новости и персональные предложения',{exact:true})).toBeChecked();await shot(page,'11-settings-desktop');
 await page.goto('/product/iphone-15-pro-max');await page.getByRole('button',{name:'В избранное',exact:true}).click();await expect.poll(async()=>await page.request.get('/api/favorites').then(r=>r.json()).then(r=>r.length)).toBe(1);
 await page.getByRole('tab',{name:/Отзывы/}).click();await page.getByRole('button',{name:'Написать отзыв'}).click();await page.getByLabel('Заголовок',{exact:true}).fill(`Браузерная проверка ${stamp}`);await page.getByLabel('Отзыв',{exact:true}).fill('Тестовая запись для проверки процесса модерации.');await page.getByRole('button',{name:'Отправить',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'модерацию'})).toBeVisible();
 expect((await page.request.get('/api/admin/users')).status()).toBe(403);
 await page.goto('/account');await page.getByRole('button',{name:'Выйти',exact:true}).click();await expect(page).toHaveURL(/auth/);await page.getByRole('button',{name:'Регистрация',exact:true}).click();await page.getByLabel('Ваше имя',{exact:true}).fill('Второй покупатель');await page.getByLabel('Электронная почта',{exact:true}).fill(`browser-second-${stamp}@velmren.local`);await page.getByLabel('Пароль',{exact:true}).fill('BrowserCheck2026!');await page.getByRole('button',{name:'Создать аккаунт'}).click();await expect(page).toHaveURL(/account\/orders/);await page.goto('/favorites');await expect(page.locator('.saved-grid .product-card')).toHaveCount(0);expect(await page.request.get('/api/favorites').then(r=>r.json())).toEqual([]);
 const admin=await browser.newContext({baseURL:'http://localhost:3210'});const ap=await admin.newPage();await ap.goto('/auth');await ap.getByLabel('Электронная почта',{exact:true}).fill('admin@velmren.local');await ap.getByLabel('Пароль',{exact:true}).fill(demoPassword());await ap.getByRole('button',{name:'Войти',exact:true}).last().click();await expect(ap).toHaveURL(/account\/orders/);await ap.goto('/admin/reviews');await ap.getByLabel('Поиск: Отзывы').fill(`Браузерная проверка ${stamp}`);await ap.getByRole('button',{name:'Открыть',exact:true}).click();await ap.getByLabel('Решение модерации').selectOption('APPROVED');await ap.getByRole('button',{name:'Сохранить изменения'}).click();await expect(ap.getByRole('dialog')).not.toBeVisible();await shot(ap,'12-admin-moderation');
 await page.goto('/product/iphone-15-pro-max');await page.getByRole('tab',{name:/Отзывы/}).click();await expect(page.getByRole('heading',{name:`Браузерная проверка ${stamp}`})).toBeVisible();
 expect(errors).toEqual([]);await admin.close();
});

test('Мобильные сравнение, избранное, корзина, checkout, заказ и кабинет',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/auth');await page.getByLabel('Электронная почта',{exact:true}).fill('buyer@velmren.local');await page.getByLabel('Пароль',{exact:true}).fill(demoPassword());await page.getByRole('button',{name:'Войти',exact:true}).last().click();await expect(page).toHaveURL(/account\/orders/);
 const order=await page.request.get('/api/orders').then(r=>r.json()).then(r=>r[0]);await page.request.post(`/api/orders/${order.id}/repeat`,{data:{}});
 await page.goto('/product/iphone-15-pro-max');await page.getByRole('button',{name:'Сравнить',exact:true}).click();await page.goto('/product/iphone-13-pro');await page.getByRole('button',{name:'Сравнить',exact:true}).click();
 for(const [url,name,ready] of [['/compare','06-compare-mobile','.comparison-table'],['/favorites','07-favorites-mobile','.saved-grid'],['/cart','08-cart-mobile','.commerce-cart-item'],['/checkout','09-checkout-mobile','.commerce-summary'],[`/orders/${order.id}`,'10-order-mobile','.commerce-order-columns'],['/account/orders','11-account-mobile','.commerce-account-order']] as const){await page.goto(url);await expect(page.locator(ready).first()).toBeVisible();await shot(page,name)}
});

test('Администратор создаёт, изменяет и удаляет бренд через интерфейс',async({page})=>{
 const name=`QA brand ${Date.now()}`;await page.goto('/auth');await page.getByLabel('Электронная почта',{exact:true}).fill('admin@velmren.local');await page.getByLabel('Пароль',{exact:true}).fill(demoPassword());await page.getByRole('button',{name:'Войти',exact:true}).last().click();await expect(page).toHaveURL(/account\/orders/);
 await page.goto('/admin/brands');await page.getByRole('button',{name:'Добавить',exact:true}).click();await page.getByLabel('Название бренда',{exact:true}).fill(name);await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await page.getByLabel('Поиск: Бренды').fill(name);await expect(page.locator('tbody tr')).toHaveCount(1);
 await page.getByRole('button',{name:'Изменить',exact:true}).click();await page.getByLabel('Название бренда',{exact:true}).fill(`${name} edited`);await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.locator('tbody')).toContainText(`${name} edited`);
 await page.getByRole('button',{name:`Удалить ${name} edited`,exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Удалить',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.locator('tbody tr')).toHaveCount(0);
});
