import {test,expect,type Page} from '@playwright/test';
import {demoPassword} from './credentials';
const output='E:/Astra/2026-09-26/realtime-voice-chat/outputs/electronics-store/revision/screenshots';
async function shot(page:Page,name:string){await expect(page.locator('.commerce-loading,.loading')).toHaveCount(0);await page.locator('img').evaluateAll(async images=>{images.forEach(i=>(i as HTMLImageElement).loading='eager');await Promise.all(images.map(i=>(i as HTMLImageElement).decode().catch(()=>{})))});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:`${output}/${name}.png`,fullPage:true,animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()}
async function login(page:Page,email='admin@velmren.local'){await page.goto('/auth');await page.getByLabel('Электронная почта',{exact:true}).fill(email);await page.getByLabel('Пароль',{exact:true}).fill(demoPassword());await page.getByRole('button',{name:'Войти',exact:true}).last().click();await expect(page).toHaveURL(/account\/orders/)}

test('Главная: разные композиции, промокод, выровненные CTA, адаптивность и reduced motion',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto('/');await expect(page.locator('.scene-phone')).toBeVisible();await page.getByRole('button',{name:'Приостановить автоматическую смену баннеров'}).click();await shot(page,'01-hero-slide-1');
 await page.getByRole('button',{name:'Следующий баннер'}).click();await expect(page.locator('.hero-slide')).toHaveCount(1);await expect(page.locator('.hero-composition-work')).toBeVisible();await expect(page.locator('.scene-phone')).toHaveCount(0);await shot(page,'01-hero-slide-2');
 await page.getByRole('button',{name:'Следующий баннер'}).click();await expect(page.locator('.hero-slide')).toHaveCount(1);await expect(page.locator('.scene-headphones')).toBeVisible();await shot(page,'01-hero-slide-3');
 const ctas=await page.locator('.promo-cta').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().bottom));expect(Math.max(...ctas)-Math.min(...ctas)).toBeLessThan(2);await page.getByRole('button',{name:'Скопировать промокод WELCOME10'}).click();await expect(page.getByRole('button',{name:'Промокод WELCOME10 скопирован'})).toBeVisible();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('WELCOME10');
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Показать предложение: Технологии ближе'}).click();await expect(page.locator('.hero-slide')).toHaveCount(1);await shot(page,'01-home-mobile');await page.emulateMedia({reducedMotion:'reduce'});await expect(page.locator('.hero-playback')).toHaveCount(0);await page.getByRole('button',{name:'Следующий баннер'}).click();await expect(page.locator('.hero-composition-work')).toBeVisible();await shot(page,'01-reduced-motion-mobile');
});

test('Фотографии соответствуют всем цветам; сортировка, подкатегории, открытый select',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/product/iphone-15-pro-max');await expect(page.locator('.product-purchase h1')).toContainText('iPhone 15 Pro Max');const data=await page.request.get('/api/products/iphone-15-pro-max').then(r=>r.json());const colors=[...new Set(data.variants.map((v:any)=>v.color))] as string[];expect(colors).toHaveLength(4);const imageUrls=new Set<string>();for(const color of colors){await page.getByRole('button',{name:`Цвет: ${color}`,exact:true}).click();const image=page.locator('.main-image-button img');await expect(image).toHaveAttribute('alt',new RegExp(color));const source=await image.getAttribute('src');imageUrls.add(source!);expect(data.variants.find((v:any)=>v.color===color).images).toContain(source);expect(await page.locator('.gallery-thumbs button').count()).toBeGreaterThanOrEqual(2)}expect(imageUrls.size).toBe(4);await shot(page,'02-color-gallery');
 await page.getByRole('button',{name:'512 ГБ',exact:true}).click();await expect(page.locator('.variant-field').last()).toContainText('512 ГБ');await page.getByRole('button',{name:'Увеличить изображение товара'}).click();await expect(page.locator('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('dialog')).not.toBeVisible();
 await page.goto('/category/smartphones');await expect(page.locator('.product-card')).toHaveCount(12);await page.getByLabel('Сортировка товаров').selectOption('price-asc');await expect(page).toHaveURL(/sort=price-asc/);await expect(page.locator('.loading')).toHaveCount(0);await page.getByLabel('Сортировка товаров').click();await expect.poll(()=>page.getByLabel('Сортировка товаров').evaluate(el=>getComputedStyle(el,'::picker(select)').opacity)).toBe('1');await page.screenshot({path:`${output}/04-select-open.png`,animations:'disabled'});await page.keyboard.press('Escape');await shot(page,'04-category-desktop');
 const subcategories=page.locator('.subcategory-pills button');expect(await subcategories.count()).toBeGreaterThan(1);await subcategories.last().click();await expect(page).toHaveURL(/subcategory=/);await expect(page.locator('.loading')).toHaveCount(0);await shot(page,'04-subcategory');await page.setViewportSize({width:390,height:844});await page.goto('/product/iphone-15-pro-max');await expect(page.locator('.color-options')).toBeVisible();await shot(page,'02-product-mobile');expect(errors).toEqual([]);
});

test('Гостевая покупка, промокод, ошибка и повтор оплаты, регистрация сохраняет заказ',async({page,browser})=>{
 // Signs in as administrator later on; skip up front when DEMO_PASSWORD is missing.
 demoPassword();
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const email=`guest-browser-${Date.now()}@velmren.local`;
 await page.goto('/product/iphone-15');await expect(page.locator('.product-purchase h1')).toBeVisible();await page.getByRole('button',{name:'Цвет: Розовый',exact:true}).click();await page.locator('.purchase-actions').getByRole('button',{name:'В корзину',exact:true}).click();await page.goto('/cart');await expect(page.locator('.commerce-cart-item')).toHaveCount(1);await expect(page.locator('.commerce-cart-info')).toContainText('Розовый');await page.getByLabel('Промокод',{exact:true}).fill('NOTVALID');await page.getByRole('button',{name:'Применить',exact:true}).click();await expect(page.locator('.promo-error')).toBeVisible();await shot(page,'08-promo-error');await page.getByLabel('Промокод',{exact:true}).fill('WELCOME10');await page.getByRole('button',{name:'Применить',exact:true}).click();await expect(page.locator('.promo-result')).toContainText('Промокод применён');await shot(page,'08-promo-success');await page.getByRole('button',{name:'Удалить промокод WELCOME10'}).click();await expect(page.locator('.promo-result')).toHaveCount(0);await page.getByLabel('Промокод',{exact:true}).fill('WELCOME10');await page.getByRole('button',{name:'Применить',exact:true}).click();await expect(page.locator('.promo-result')).toBeVisible();
 await page.getByRole('link',{name:'Оформить заказ',exact:true}).click();await expect(page.getByRole('heading',{name:'Контактные данные',exact:true})).toBeVisible();await page.getByRole('button',{name:'Оформить заказ',exact:true}).click();await expect(page.getByText('Введите имя',{exact:true})).toBeVisible();for(const [label,value] of [['Имя и фамилия','Гость Проверка'],['Электронная почта',email],['Телефон','+7 999 222-33-44'],['Улица, дом, квартира','Улица Покупок, 7, 12']])await page.getByLabel(label,{exact:true}).fill(value);await shot(page,'09-guest-checkout');await page.getByRole('button',{name:'Оформить заказ',exact:true}).click();await expect(page).toHaveURL(/\/orders\//);const orderId=page.url().split('/').pop()!;await expect(page.getByRole('heading',{name:'Сохраните заказ в личном кабинете'})).toBeVisible();await shot(page,'10-guest-order');
 const outsider=await browser.newContext({baseURL:'http://localhost:3210'});expect((await outsider.request.get(`/api/orders/${orderId}`)).status()).toBeGreaterThanOrEqual(400);await outsider.close();
 const failed=await page.request.post(`/api/orders/${orderId}/payment`,{data:{result:'failure',eventId:`browser-failure-${Date.now()}`}});expect(failed.ok()).toBeTruthy();await page.reload();await page.getByRole('button',{name:'Повторить оплату',exact:true}).click();await expect(page.getByText('Оплачен',{exact:true}).first()).toBeVisible();
 await page.getByRole('link',{name:'Создать аккаунт',exact:true}).click();await expect(page.getByLabel('Ваше имя',{exact:true})).toHaveValue('Гость Проверка');await expect(page.getByLabel('Электронная почта',{exact:true})).toHaveValue(email);await page.getByLabel('Пароль',{exact:true}).fill('GuestBrowser2026!');await page.getByRole('button',{name:'Создать аккаунт',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/orders/${orderId}`));await expect(page.getByRole('heading',{name:'Сохраните заказ в личном кабинете'})).toHaveCount(0);const orders=await page.request.get('/api/orders').then(r=>r.json());expect(orders.some((o:any)=>o.id===orderId)).toBeTruthy();await page.goto('/account/orders');await expect(page.locator('.commerce-account-order')).toHaveCount(1);await shot(page,'11-claimed-order');const profile=await page.request.get('/api/profile').then(r=>r.json());expect(profile.phone).toBe('+7 999 222-33-44');expect(profile.addresses.some((a:any)=>a.street==='Улица Покупок, 7, 12')).toBeTruthy();
 const admin=await browser.newContext({baseURL:'http://localhost:3210'});const ap=await admin.newPage();await login(ap);await ap.goto('/admin/orders');await ap.getByLabel('Поиск: Заказы').fill(orders[0].number);await ap.getByRole('button',{name:'Открыть',exact:true}).click();await ap.getByLabel('Статус заказа').selectOption('SHIPPED');await ap.getByRole('button',{name:'Сохранить изменения'}).click();await expect(ap.getByRole('dialog')).not.toBeVisible();await page.goto(`/orders/${orderId}`);await expect(page.getByText('Доставляется',{exact:true}).first()).toBeVisible();await shot(page,'10-order-shipped');await admin.close();expect(errors).toEqual([]);
});

test('Информационные страницы, FAQ, отсутствие служебных подписей и мобильные формы',async({page})=>{
 for(const slug of ['delivery','payment','warranty','returns','about','contacts','privacy','terms']){await page.goto(`/service/${slug}`);await expect(page.locator('.service-page-hero h1')).toBeVisible();expect((await page.locator('.service-content').innerText()).length).toBeGreaterThan(600);expect(await page.locator('body').innerText()).not.toMatch(/демо|учебный|портфолио|TEST MODE|тестов/iu);if(await page.locator('.service-faq summary').count()){await page.locator('.service-faq summary').first().click();await expect(page.locator('.service-faq details').first()).toHaveAttribute('open','')}if(slug==='delivery')await shot(page,'15-delivery-desktop')}
 await page.setViewportSize({width:390,height:844});for(const [url,name] of [['/service/delivery','15-delivery-mobile'],['/catalog','03-catalog-mobile'],['/search?q=iPhone','05-search-mobile'],['/auth','14-auth-mobile']]){await page.goto(url);await expect(page.locator('main h1').first()).toBeVisible();await shot(page,name);expect(await page.locator('body').innerText()).not.toMatch(/демо|учебный|портфолио|TEST MODE/iu)}await page.goto('/');await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'К основному содержанию'})).toBeFocused();
});

test('Первый визит не теряет корзину из-за задержанного каталога; нет активных вариантов',async({page})=>{
 let release!:()=>void;const gate=new Promise<void>(r=>release=r);await page.route('**/api/catalog?limit=100',async route=>{const response=await route.fetch();await gate;await route.fulfill({response})});await page.goto('/');const catalog=await page.request.get('/api/catalog?category=smartphones&limit=1').then(r=>r.json());const variant=catalog.products[0].variants[0];await page.request.post('/api/cart',{data:{variantId:variant.id,quantity:1}});release();await expect(page.locator('.storefront-hero')).toBeVisible();await page.goto('/cart');await expect(page.locator('.commerce-cart-item')).toHaveCount(1);
 await page.route('**/api/products/iphone-15-pro-max',async route=>{const response=await route.fetch();const data=await response.json();await route.fulfill({json:{...data,variants:[],stock:0}})});await page.goto('/product/iphone-15-pro-max');await expect(page.getByText('Сейчас эта модель недоступна для заказа.')).toBeVisible();await expect(page.getByRole('link',{name:'Посмотреть похожие товары'})).toBeVisible();
});
