'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {HomeHero} from './home-hero';
import {ArrowRight,Check,Copy} from 'lucide-react';
import {Catalog,Product,categoryLabels} from '@/lib/types';
import {useResource} from '@/lib/client';
import {Benefits,Breadcrumb,ErrorState,Loading,ProductGrid,SectionTitle,ServiceStrip} from './store-ui';
const categoryCopy:Record<string,string>={smartphones:'Всегда на связи',laptops:'Для работы и вдохновения',tablets:'Больше возможностей',audio:'Ваш идеальный звук',watches:'В ритме вашей жизни',gaming:'Время новых миров',cameras:'Сохраните каждый момент','smart-home':'Комфорт начинается дома',accessories:'Всё в деталях',home:'Забота о вашем доме'};
const find=(products:Product[],category:string)=>products.find(p=>p.category===category&&p.featured)||products.find(p=>p.category===category);
export function Home(){const{data,error,loading,reload}=useResource<Catalog>('/api/catalog?limit=100');const[tab,setTab]=useState('all');if(loading)return <Loading/>;if(error||!data)return <div className="container page"><ErrorState error={error} retry={reload}/></div>;const products=data.products;const phone=find(products,'smartphones'),laptop=find(products,'laptops'),audio=find(products,'audio');const featured=tab==='all'?['smartphones','laptops','audio','watches','tablets'].map(c=>find(products,c)).filter((p):p is Product=>!!p):products.filter(p=>p.category===tab).slice(0,5);return <div className="container page"><HomeHero/><section className="store-section"><SectionTitle title="Найдите своё" label="Все категории"/><div className="category-row">{Object.entries(categoryLabels).slice(0,8).map(([slug,label])=><Link key={slug} href={`/category/${slug}`} className="category-tile">{find(products,slug)&&<img src={find(products,slug)!.images[0]} alt=""/>}<span>{label}</span></Link>)}</div><div className="promo-grid"><Promo title="Лёгкость в каждом деле" text="Ноутбуки для работы, учёбы и новых идей." product={laptop} href="/category/laptops" dark/><Promo title="Больше возможностей" text="На первый заказ. Скидка до 5 000 ₽." product={phone} href="/search?sale=true" discount/><Promo title="Только вы и музыка" text="Наушники, которые звучат по-вашему." product={audio} href="/category/audio" dark/></div></section><section className="store-section"><div className="section-title home-products-header"><h2>Стоит присмотреться</h2><div className="tabs">{[['all','Все товары'],['smartphones','Смартфоны'],['laptops','Ноутбуки'],['audio','Наушники'],['watches','Часы']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}>{label}</button>)}</div></div><ProductGrid products={featured.length?featured:products.slice(0,5)}/></section><section className="store-section"><h2>Техника с заботой о вас</h2><Benefits/></section><div className="wide-banner">{phone&&<img src={phone.images[0]} alt={phone.name}/>}<div><p className="eyebrow">Больше, чем просто связь</p><h2>Ваш следующий смартфон.</h2><p>Выберите тот, который подходит именно вам.</p></div><Link className="button" href="/category/smartphones">Смотреть коллекцию <ArrowRight size={16}/></Link></div><ServiceStrip/></div>}
function Promo({title,text,product,href,dark,discount}:{title:string;text:string;product?:Product;href:string;dark?:boolean;discount?:boolean}) {
  const [copied,setCopied]=useState(false);
  const [copyError,setCopyError]=useState(false);
  useEffect(()=>{if(!copied)return;const timer=window.setTimeout(()=>setCopied(false),2500);return()=>window.clearTimeout(timer);},[copied]);
  async function copyCode(){try{await navigator.clipboard.writeText('WELCOME10');setCopied(true);setCopyError(false);}catch{setCopyError(true);}}
  return <article className={`promo-card curated-promo ${dark?'dark':''} ${discount?'promo-welcome':''}`}>
    <div className="promo-copy"><h3>{title}</h3>{discount&&<div className="promo-price">−10<span>%</span></div>}<p>{text}</p>
      {discount&&<><button className="promo-code" onClick={copyCode} aria-label={copied?'Промокод WELCOME10 скопирован':'Скопировать промокод WELCOME10'}><span>WELCOME10</span>{copied?<Check size={13}/>:<Copy size={13}/>}</button><span className="promo-copy-feedback" role="status">{copied?'Промокод скопирован':copyError?'Введите WELCOME10 при оформлении':'Промокод на первый заказ'}</span></>}
    </div>
    <Link href={href} className="promo-cta">{discount?'Выбрать со скидкой':'Смотреть коллекцию'} <ArrowRight size={14}/></Link>
    {product&&<div className="promo-image"><img src={product.images[0]} alt="" loading="lazy"/></div>}
  </article>;
}
export function CatalogPage(){const{data,loading,error,reload}=useResource<Catalog>('/api/catalog?limit=100');if(loading)return <Loading/>;if(!data||error)return <div className="container page"><ErrorState error={error} retry={reload}/></div>;const products=data.products;const laptop=find(products,'laptops');return <div className="container page"><Breadcrumb items={[{label:'Каталог'}]}/><div className="catalog-intro"><div><p className="eyebrow">Для вашей цифровой жизни</p><h1>Каталог <span className="blue">возможностей.</span></h1><p>Техника для работы, отдыха и всего между ними. Найдите то, что сделает ваш день лучше.</p></div><div className="intro-art"><h3>Большие идеи<br/>начинаются здесь.</h3>{laptop&&<img src={laptop.images[0]} alt={laptop.name}/>}</div></div><SectionTitle title="Категории товаров" href="/search" label={`${data.total} товаров`}/><div className="category-directory">{Object.entries(categoryLabels).map(([slug,label])=><Link key={slug} href={`/category/${slug}`}><h3>{label}</h3><p>{categoryCopy[slug]}</p>{find(products,slug)&&<img src={find(products,slug)!.images[0]} alt=""/>}<span className="round-arrow"><ArrowRight size={16}/></span></Link>)}</div><section className="store-section"><h2>Ваши любимые бренды</h2><div className="brands">{data.facets.brands.slice(0,8).map(brand=><Link href={`/search?brand=${encodeURIComponent(brand)}`} key={brand}>{brand}</Link>)}</div></section><div className="wide-banner">{laptop&&<img src={laptop.images[0]} alt={laptop.name}/>}<div><p className="eyebrow">Работайте. Создавайте. Вдохновляйтесь.</p><h2>Лёгкость большого дела.</h2><p>Ноутбуки под ваши задачи.</p></div><Link href="/category/laptops" className="button">Выбрать <ArrowRight size={16}/></Link></div><section className="store-section"><h2>Подборки с характером</h2><div className="promo-grid"><Promo title="Для учёбы и работы" text="Соберите своё рабочее пространство." product={laptop} href="/category/laptops"/><Promo title="В центре игры" text="Новые миры ждут вас." product={find(products,'gaming')} href="/category/gaming" dark/><Promo title="Дом становится умнее" text="Маленькие решения для большого комфорта." product={find(products,'smart-home')} href="/category/smart-home"/></div></section><section className="store-section"><SectionTitle title="Выбор редакции" href="/search?sort=popular"/><ProductGrid products={products.filter(p=>p.featured).slice(0,5)}/></section><Benefits/></div>}
