'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowRight,ChevronRight,Heart,ShoppingCart,Scale,Truck,ShieldCheck,CreditCard,RotateCcw,Headphones,LoaderCircle,Check} from 'lucide-react';
import {Product} from '@/lib/types';
import {addToCart,api,localIds,money,notify,refreshStore,toggleLocal} from '@/lib/client';

export function Breadcrumb({items=[]}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumb" aria-label="Хлебные крошки"><Link href="/">Главная</Link>{items.map((item,i)=><span key={i}><ChevronRight size={13}/>{item.href?<Link href={item.href}>{item.label}</Link>:item.label}</span>)}</nav>}
export function Loading(){return <div className="loading" role="status"><LoaderCircle className="spin"/> Загружаем товары…</div>}
export function ErrorState({error,retry}:{error:string;retry?:()=>void}){return <div className="empty-state" role="alert"><h2>Не удалось загрузить данные</h2><p>{error}</p>{retry&&<button className="button" onClick={retry}>Повторить</button>}</div>}
export function SectionTitle({title,href='/catalog',label='Смотреть все'}:{title:string;href?:string;label?:string}){return <div className="section-title"><h2>{title}</h2><Link href={href}>{label} <ArrowRight size={16}/></Link></div>}
export function Benefits(){return <div className="benefits">{[[ShieldCheck,'Внимание к качеству','Характеристики и комплектация в карточке'],[Truck,'Доставка на ваш выбор','Курьером или в пункт выдачи'],[RotateCcw,'Помощь после покупки','Возврат и гарантийная поддержка'],[CreditCard,'Удобная оплата','Картой, СБП или при получении']].map(([Icon,title,text]:any)=><div className="benefit" key={title}><span className="icon-disc"><Icon size={27}/></span><div><strong>{title}</strong><p>{text}</p></div></div>)}</div>}
export function ServiceStrip(){return <div className="service-strip"><span className="icon-disc"><Headphones size={32}/></span><div><h3>Поможем с выбором</h3><p>Расскажите, какую технику ищете. Ответим в личном кабинете.</p></div><Link className="button secondary" href="/support">Написать нам <ArrowRight size={17}/></Link></div>}
export function ProductCard({product:p}:{product:Product}){const [favorite,setFavorite]=useState(false);const [compare,setCompare]=useState(false);const [busy,setBusy]=useState(false);const [added,setAdded]=useState(false);useEffect(()=>{const sync=()=>{setFavorite(localIds('velmren:favorites:v1').includes(p.id));setCompare(localIds('velmren:compare:v1').includes(p.id))};sync();window.addEventListener('store:refresh',sync);return()=>window.removeEventListener('store:refresh',sync)},[p.id]);const variant=p.variants?.find(v=>v.id===p.selectedVariantId)||p.variants?.find(v=>v.stock>0)||p.variants?.[0];const price=variant?.price??p.price;const old=variant?.oldPrice??p.oldPrice;async function favoriteToggle(){const next=toggleLocal('velmren:favorites:v1',p.id);setFavorite(next.includes(p.id));try{await api('/api/favorites',next.includes(p.id)?'POST':'DELETE',{productId:p.id})}catch{}notify(next.includes(p.id)?'Сохранено в избранном':'Удалено из избранного')};return <article className="product-card"><div className="product-visual"><Link href={`/product/${p.slug}`} tabIndex={-1}><img src={p.images?.[0]} alt={p.name} loading="lazy"/></Link><span className={`product-badge ${old&&old>price?'sale':''}`}>{old&&old>price?`−${Math.round((1-price/old)*100)}%`:p.badge||''}</span><div className="card-tools"><button className={favorite?'active':''} aria-label={`${favorite?'Удалить из избранного':'В избранное'}: ${p.name}`} aria-pressed={favorite} onClick={favoriteToggle}><Heart size={19} fill={favorite?'currentColor':'none'}/></button><button className={compare?'active':''} aria-label={`Сравнить: ${p.name}`} aria-pressed={compare} onClick={()=>{const ids=localIds('velmren:compare:v1');if(!compare&&ids.length>=4){notify('В сравнении может быть до 4 товаров');return}toggleLocal('velmren:compare:v1',p.id);notify(compare?'Товар убран из сравнения':'Товар добавлен в сравнение')}}><Scale size={18}/></button></div></div><div className="product-card-body"><p className="product-brand">{p.brand}</p><Link className="product-name" href={`/product/${p.slug}`}>{p.name}</Link><div className="product-rating">{p.reviewCount>0?<><span>★</span> {p.rating.toFixed(1)} <span className="muted">({p.reviewCount})</span></>:<span className="muted">Пока нет отзывов</span>}</div><div className="product-prices"><strong>{money(price)}</strong>{old&&old>price?<s>{money(old)}</s>:null}</div><div className={`availability ${variant?.stock?'':'out'}`}>{variant?.stock?(variant.stock<4?`Осталось ${variant.stock} шт.`:'В наличии'):'Нет в наличии'}</div><button className="button card-buy" disabled={busy||!variant?.stock} onClick={async()=>{setBusy(true);try{await addToCart(variant.id);setAdded(true)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}>{busy?<LoaderCircle size={17} className="spin"/>:added?<Check size={17}/>:<ShoppingCart size={17}/>} {added?'В корзине':'В корзину'}</button></div></article>}
export function ProductGrid({products,className=''}:{products:Product[];className?:string}){return <div className={`product-grid ${className}`}>{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>}
export function Empty({title,text,icon='heart'}:{title:string;text:string;icon?:string}){return <div className="empty-state"><span className="icon-disc">{icon==='heart'?<Heart size={34}/>:<ShoppingCart size={34}/>}</span><h2>{title}</h2><p>{text}</p><Link href="/catalog" className="button">Перейти в каталог <ArrowRight size={18}/></Link></div>}
