const examples={
  "npc": "npcs:\n  guard:\n    name: '&cСтраж Илья'\n    role: Патруль северных ворот\n    world: npc_demo\n    x: 0\n    y: 65\n    z: -26\n    profession: ARMORER\n    dialogue: guard\n    interval: 10\n    speed: 0.2\n    route:\n      - {x: 0, y: 65, z: -26}\n      - {x: 5, y: 65, z: -26}\n      - {x: -5, y: 65, z: -26}",
  "dialogue": "dialogs:\n  elder:\n    start: start\n    nodes:\n      start:\n        text: 'Добро пожаловать, {player}. Гавани нужны умелые руки. С чего начнёшь?'\n        choices:\n          - text: Расскажи о деревне\n            next: history\n          - text: Я познакомлюсь с кузнецом\n            conditions: [{type: active, quest: welcome, not: true}, {type: completed, quest: welcome, not: true}]\n            actions: [{type: quest, quest: welcome}]\n          - text: Получить награду за знакомство\n            conditions: [{type: active, quest: welcome}]\n            actions: [{type: complete, quest: welcome}]\n          - text: Кому сейчас нужна помощь?\n            conditions: [{type: completed, quest: welcome}]\n            next: work\n      history:\n        text: 'Мельница остановилась, а маяк погас. Олег, Мара и Ника ждут помощи — но сперва заслужи их доверие.'\n        choices:\n          - {text: Предпочитаю полезную работу, next: start, actions: [{type: variable, key: approach, value: practical}]}\n          - {text: Сперва хочу осмотреться, next: start, actions: [{type: variable, key: approach, value: explorer}]}\n      work:\n        text: 'Олегу нужна древесина, Павлу — урожай. Илья охраняет северные ворота, а Анна составляет карту побережья. Твой путь: {var:approach}.'\n        choices:\n          - {text: Спасибо}",
  "quest": "quests:\n  mill:\n    name: Мельничное колесо\n    requires: [welcome]\n    stages:\n      - {type: COLLECT, material: OAK_LOG, amount: 8}\n      - {type: DELIVER, npc: lumberjack, material: OAK_LOG, amount: 8}\n    rewards:\n      - {type: money, amount: 8}\n      - {type: block, world: npc_demo, x: -35, y: 66, z: -10, material: OAK_PLANKS}\n      - {type: message, text: 'Недостающая ступица мельничного колеса восстановлена.'}",
  "shop": "shops:\n  market:\n    goods:\n      - {material: BREAD, amount: 3, buy: 2, sell: 1}\n      - {material: WHEAT, amount: 4, buy: 3, sell: 1}\n      - {material: OAK_LOG, amount: 8, buy: 6, sell: 2}\n      - {material: IRON_INGOT, amount: 4, buy: 8, sell: 3}\n      - {material: GLASS, amount: 4, buy: 4, sell: 1}\n      - {material: STONE_AXE, amount: 1, buy: 3}"
};
let currentCode='npc';
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showCode(id){currentCode=id;document.querySelectorAll('[data-code]').forEach(b=>{const selected=b.dataset.code===id;b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1});document.querySelector('#code-block code').innerHTML=examples[id].split('\n').map(l=>{let safe=escape(l);if(l.trim().startsWith('#'))safe='<span class="yaml-comment">'+safe+'</span>';else safe=safe.replace(/^(\s*)([\w-]+)(:)/,'$1<span class="yaml-key">$2</span>$3').replace(/(&quot;.*?&quot;|\b(?:true|false|NATIVE|EMERALD|TALK|COLLECT|OAK_LOG|BREAD)\b)/g,'<span class="yaml-value">$1</span>');return '<span class="line">'+(safe||' ')+'</span>'}).join('');document.querySelector('#copy-status').textContent='';}
document.querySelectorAll('[data-code]').forEach(b=>b.addEventListener('click',()=>showCode(b.dataset.code)));
showCode('npc');
fetch('assets/config-examples.json').then(r=>r.ok?r.json():null).then(data=>{if(data){Object.assign(examples,data);showCode(currentCode);document.querySelector('.code-footer>span').textContent='YAML · фрагмент конфигурации плагина';}}).catch(()=>{});
document.querySelector('.copy').addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText(examples[currentCode]);status.textContent='Скопировано ✓';}catch{status.textContent='Выделите YAML и скопируйте вручную';}});
const stories={mill:{number:'01',title:'Верните мельнице жизнь',location:'МЕЛЬНИЦА И ФЕРМА',description:'Поговорите со старостой, соберите материалы и передайте их лесорубу. Цепочка связывает жителей и приводит к видимому ремонту.',steps:['Разговор и принятие задания','Сбор и доставка ресурсов','Завершение этапа и награда']},harbor:{number:'02',title:'Соберите припасы для гавани',location:'РЫНОК И ПРИЧАЛ',description:'Помогите жителям подготовить припасы. Исследуйте рынок, используйте магазин и доставьте нужные предметы персонажу.',steps:['Встреча с жителями на рынке','Покупка или сбор предметов','Доставка и получение награды']},forest:{number:'03',title:'Зажгите огонь на маяке',location:'КУЗНИЦА И МАЯК',description:'После ремонта мельницы помогите кузнецу с железом, поднимитесь на маяк и доставьте стекло хранителю. Финальный этап возвращает свет гавани.',steps:['Железо для кузнеца после ремонта мельницы','Подъём на маяк и доставка стекла','Настройка линзы и возвращение света']}};
document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-scenario]').forEach(x=>{const selected=x===b;x.setAttribute('aria-selected',selected);x.tabIndex=selected?0:-1});const d=stories[b.dataset.scenario];for(const k of ['number','title','description','location'])document.querySelector('#scenario-'+k).textContent=d[k];document.querySelector('#scenario-steps').innerHTML=d.steps.map(s=>'<li>'+escape(s)+'</li>').join('');document.querySelector('.scenario-art').style.backgroundPosition=b.dataset.scenario==='harbor'?'75% 45%':b.dataset.scenario==='forest'?'30% 15%':'center 30%';}));
document.querySelectorAll('[role=tablist]').forEach(list=>list.addEventListener('keydown',e=>{const buttons=[...list.querySelectorAll('[role=tab]')];const index=buttons.indexOf(document.activeElement);if(index<0)return;let next;if(e.key==='ArrowRight')next=(index+1)%buttons.length;if(e.key==='ArrowLeft')next=(index-1+buttons.length)%buttons.length;if(e.key==='Home')next=0;if(e.key==='End')next=buttons.length-1;if(next!==undefined){e.preventDefault();buttons[next].click();buttons[next].focus();}}));
const dialogueResponses={accept:{text:'Начни с материалов для ремонта. Поговори с лесником, собери древесину и вернись к лесорубу. Каждое задание приближает гавань к восстановлению.',choices:[['reset','Понятно. Вернусь с материалами.']]},reward:{text:'Награда задаётся в конфигурации квеста: предметы, валюта и новые возможности. В демо завершённые этапы открывают продолжение истории.',choices:[['accept','Что нужно сделать?'],['reset','Вернуться к разговору']]},later:{text:'Гавань будет ждать. Возвращайся, когда захочешь продолжить историю.',choices:[['reset','Начать разговор снова']]},reset:{text:'Добро пожаловать в гавань. Старой мельнице нужна помощь. Возьмёшься за дело?',choices:[['accept','Что нужно сделать?'],['reward','Какая награда?'],['later','Я вернусь позже.']]}};
document.querySelector('#dialogue-choices').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=dialogueResponses[b.dataset.choice];document.querySelector('#dialogue-text').textContent=d.text;document.querySelector('#dialogue-choices').innerHTML=d.choices.map(([key,label])=>'<button data-choice="'+key+'"><span>▸</span>'+escape(label)+'</button>').join('');document.querySelector('#dialogue-choices button').focus();});
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');document.querySelector('.nav nav').classList.toggle('open',open)});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');document.querySelector('.nav nav').classList.remove('open')}));
fetch('assets/game-gallery.json').then(r=>r.ok?r.json():null).then(data=>{if(!data?.length)return;const gallery=document.querySelector('#game-gallery');gallery.hidden=false;gallery.querySelector('.game-images').innerHTML=data.map(item=>'<figure><a href="'+escape(item.src)+'" target="_blank" rel="noopener"><img loading="lazy" src="'+escape(item.src)+'" alt="'+escape(item.caption)+'"></a><figcaption>'+escape(item.caption)+'</figcaption></figure>').join('');}).catch(()=>{});
fetch('assets/release-status.json').then(r=>r.ok?r.json():null).then(data=>{if(!data)return;for(const runtime of ['paper','spigot','purpur'])if(data[runtime]){const el=document.querySelector('#'+runtime+'-status');el.textContent=data[runtime].label;el.classList.toggle('pending',!data[runtime].verified)}if(data.downloadLabel)document.querySelector('#download-status').textContent=data.downloadLabel;}).catch(()=>{});




